# Generated by Django 3.0.14 on 2022-07-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220719_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
